<?php

/**
 * @file
 * codemirror hook implementations.
 */

/**
 * Implements hook_library_info_alter().
 *
 * Dynamically attach libraries for codemirror plugins.
 */
function codemirror_library_info_alter(&$libraries, $module) {
  if ($module == 'codemirror') {
    /* @var \Drupal\Component\Plugin\PluginManagerInterface $pluginManager */
    $pluginManager = Drupal::service('plugin.manager.codemirror');
    foreach ($pluginManager->getDefinitions() as $plugin_id => $info) {
      /* @var \Drupal\codemirror\CodeMirrorPluginInterface $plugin */
      $plugin = $pluginManager->createInstance($plugin_id);
      $libraries['codemirror.plugin.' . $info['id']] = $plugin->buildLibrary();
    }
  }
}
